import './globals.css'
import { Roboto } from 'next/font/google'
import FavIcon from './favicon-32x32.png'

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '700']
})

export const metadata = {
  title: 'Newsletter Sign-up',
  description: 'Generated by create next app',
  icons: [
    {
      rel: 'icon',
      type: 'image/png',
      sizes: '32x32',
      url: '../../public/favicon-32x32.png',
    },
  ]
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${roboto.className} min-h-screen
       text-Dark-Slate-Grey text-md bg-Dark-Slate-Grey grid place-content-center`}>
        {children}
      </body>
    </html>
  )
}
